services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nitsan\NsOpenStreetmap\:
    resource: '../Classes/*'

  Nitsan\NsOpenStreetmap\Controller\AddressController:
    public: true
    arguments:
      $addressRepository: '@Nitsan\NsOpenStreetmap\Domain\Repository\AddressRepository'
      